baseurl = "https://example.com"
languageCode = "en-us"
theme = "omstest-theme"
paginate = 5
title = "Example Site"
disqusShortname = "omstest-theme"
DefaultContentLanguage = "en"
hasCJKLanguage = false
googleAnalytics = ""

[languages.en]
  languageName = "English"
  title = "Example Site"
  weight = 1

[languages.zh-cn]
  languageName = "中文"
  title = "演示站点"
  weight = 2

[languages.ar]
  languageName = "عربي"
  languagedirection = "rtl"
  title = "موقع تجريبي"
  weight = 3

[permalinks]
  post = "/p/:slug/"
  page = "/:slug/"

[params]
  mainSections = [ "post" ]
  featuredImageField = "image"
  rssFullContent = true
  favicon = ""

  [params.footer]
    since = 2_020
    customText = ""

  [params.dateFormat]
    published = "Jan 02, 2006"
    lastUpdated = "Jan 02, 2006 15:04 MST"

  [params.sidebar]
    emoji = "🍥"
    subtitle = "Lorem ipsum dolor sit amet, consectetur adipiscing elit."

      [params.sidebar.avatar]
        enabled = true
        local = true
        src = "img/avatar.png"

  [params.article]
    math = false
    toc = true
    readingTime = true

    [params.article.license]
      enabled = true
      default = "Licensed under CC BY-NC-SA 4.0"

  [params.comments]
    enabled = true
    provider = "disqus"

    [params.comments.disqusjs]
      shortname = ""
      apiUrl = ""
      apiKey = ""
      admin = ""
      adminLabel = ""

    [params.comments.utterances]
      repo = ""
      issueTerm = "pathname"
      label = ""

    [params.comments.remark42]
      host = ""
      site = ""
      locale = ""

    [params.comments.vssue]
      platform = ""
      owner = ""
      repo = ""
      clientId = ""
      clientSecret = ""
      autoCreateIssue = false

    [params.comments.waline]
      serverURL = ""
      lang = ""
      pageview = ""
      emoji = [ "https://unpkg.com/@waline/emojis@1.0.1/weibo" ]
      requiredMeta = [ "name", "email", "url" ]

      [params.comments.waline.locale]
        admin = "Admin"
        placeholder = ""

    [params.comments.twikoo]
      envId = ""
      region = ""
      path = ""
      lang = ""

    [params.comments.cactus]
      defaultHomeserverUrl = "https://matrix.cactus.chat:8448"
      serverName = "cactus.chat"
      siteName = ""

    [params.comments.giscus]
      repo = ""
      repoID = ""
      category = ""
      categoryID = ""
      mapping = ""
      lightTheme = ""
      darkTheme = ""
      reactionsEnabled = 1
      emitMetadata = 0

    [params.comments.gitalk]
      owner = ""
      admin = ""
      repo = ""
      clientID = ""
      clientSecret = ""

    [params.comments.cusdis]
      host = ""
      id = ""

[[params.widgets.homepage]]
  type = "search"

[[params.widgets.homepage]]
  type = "archives"

  [params.widgets.homepage.params]
    limit = 5

[[params.widgets.homepage]]
  type = "categories"

  [params.widgets.homepage.params]
    limit = 10

[[params.widgets.homepage]]
  type = "tag-cloud"

  [params.widgets.homepage.params]
    limit = 10

[[params.widgets.page]]
  type = "toc"

[params.opengraph.twitter]
  site = ""
  card = "summary_large_image"

[params.defaultImage.opengraph]
  enabled = false
  local = false
  src = ""

  [params.colorScheme]
    toggle = true
    default = "auto"

[params.imageProcessing.cover]
  enabled = true

[params.imageProcessing.content]
  enabled = true

[menu]
  main = [ ]

  [[menu.social]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/CaiJimmy/hugo-theme-stack"

    [menu.social.params]
      icon = "brand-github"

  [[menu.social]]
    identifier = "twitter"
    name = "Twitter"
    url = "https://twitter.com"

    [menu.social.params]
      icon = "brand-twitter"

[related]
  includeNewer = true
  threshold = 60
  toLower = false

  [[related.indices]]
    name = "tags"
    weight = 100

  [[related.indices]]
    name = "categories"
    weight = 200

[markup.goldmark.renderer]
  unsafe = false

[markup.tableOfContents]
  endLevel = 4
  ordered = true
  startLevel = 2

[markup.highlight]
  noClasses = false
  codeFences = true
  guessSyntax = true
  lineNoStart = 1
  lineNos = true
  lineNumbersInTable = true
  tabWidth = 4
